// Living-battlefield BALANCE — the single source of truth for the soldier/Intendant
// simulation tuning, kept in the SAME key schema the lab (design/battlefield-lab.html)
// exports. Regenerate from a lab export with:
//
//     node scripts/apply-lab-params.mjs <lab-export.json>
//
// The lab's "Exporter JSON" button emits { seed, params, spawnMode, weapon }; the
// script lifts `params` verbatim into this file. battlefield.js merges it OVER its
// built-in DEFAULT_PARAMS, so:
//   • keys present here override the engine default (live tuning);
//   • engine-only keys absent here keep their default;
//   • lab keys not yet consumed by the engine are harmless until the logic port.
//
// DO NOT hand-edit for balance changes — tune in the lab, export, run the script.

export default {
  "v0": 40,
  "fallHmin": 7,
  "fallHmax": 26,
  "fallDmg": 2.5,
  "engage": 12,
  "sHp": 4,
  "spacing": 18,
  "spawnFreq": 4.4,
  "doorT": 0.26,
  "archerPct": 0.12,
  "arHp": 2,
  "arDmg": 3,
  "arRange": 80,
  "desertT": 4,
  "repTime": 4,
  "musRange": 160,
  "musDmg": 3,
  "chargeRange": 70,
  "ballDmg": 4.5,
  "splashFactor": 0.5,
  "musAcc": 0.78,
  "musSpread": 0.045,
  "musMissSpread": 0.22,
  "musDmgVar": 1,
  "bowAcc": 0.76,
  "bowSpread": 0.035,
  "bowMissSpread": 0.31,
  "bowDmgVar": 0.85,
  "pathCongestion": 3.5,
  "pathJitter": 0.4,
  "slopeFx": 0.25,
  "ballSpeed": 470,
  "musSpeed": 480,
  "bowSpeed": 440,
  "boltSpeed": 380,
  "grenTime": 0.6,
  "grenLob": 120,
  "mqSpdMul": 1,
  "mqFallMul": 1,
  "grSpdMul": 1.15,
  "grFallMul": 0.9,
  "caSpdMul": 0.4,
  "caFallMul": 2.5,
  "enSpdMul": 0.9,
  "enFallMul": 1.5,
  "sJump": 8,
  "mqJumpMul": 1,
  "grJumpMul": 1.05,
  "caJumpMul": 0,
  "enJumpMul": 1.1,
  "cataHp": 5,
  "engHp": 3,
  "engBridgeMax": 6,
  "engLadH": 40,
  "engLadRun": 52,
  "cataRange": 240,
  "towerDmg": 99,
  "towerBolts": 4,
  "intSpeed": 120,
  "jumpV": 240,
  "glide": 55,
  "climbSpeed": 10,
  "swordR": 28,
  "swDmg": 4,
  "bowDmg": 2.5,
  "bowRange": 210,
  "digSpeed": 40,
  "digH": 4,
  "buildSteps": 4,
  "grav": 900,
  "climbSlope": 1.3,
  "maxHp": 3,
  "towerWarn": 150,
  "towerFire": 95,
  "towerRate": 1.6,
  "craterR": 24,
  "ballCraterR": 24,
  "grenCraterR": 9,
  "shieldR": 54,
  "shieldDur": 1.5,
  "bayoDmgVar": 0.3,
  "grenDmgVar": 1.5,
  "ballDmgVar": 0.5,
  "swDmgVar": 0.45,
  "bayoWind": 0.15,
  "bayoRec": 0.45,
  "bayoDmg": 2,
  "musWind": 0.6,
  "musRec": 1.6,
  "grenWind": 0.6,
  "grenRec": 0.15,
  "cataWind": 1.8,
  "cataRec": 1.6,
  "engWind": 0.3,
  "engRec": 0.3,
  "engDur": 0.22,
  "swWind": 0.2,
  "swRec": 0.3,
  "bowWind": 0.25,
  "bowRec": 0.3,
  "toolWind": 0.18,
  "toolRec": 0.18,
  "toolDur": 0.12,
  "buildWind": 0.25,
  "buildRec": 0.3,
  "buildDur": 0.26
};
